# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Pipeline 
# Trigger the workflow on specific events, such as a push or pull request 
on:
 push: 
    branches: 
     - main 
 # Jobs and steps for the workflow 
jobs:
   deploy:
     runs-on: ubuntu-latest 
     steps: 
 # Checkout the git repository 
       - name: Checkout 
         uses: actions/checkout@v2 
 # Install any dependencies needed for deployment 
       - name: Install Dependencies 
         run: | 
              npm install 
 # or any other package manager specific to your environment
 # Build and deploy the pipeline 
       - name: Build and Deploy 
          run:| 
                npm run build 
 # or any other build command specific to your environment 
 # deploy the pipeline using your deployment process
