# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Pipeline

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Ckeckout repository
      uses: actions/checkout@v2
      with:
        node-version: '18,x'

    - name: Setup Node.js enviornment
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependecies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test
